export enum Section {
  PROSPECTIVE = "PROSPECTIVE",
  ACADEMIC = "ACADEMIC",
  RESEARCH = "RESEARCH",
  PEOPLE = "PEOPLE",
  NEWS = "NEWS",
  EMPLOYMENT = "EMPLOYMENT",
  DONATE = "DONATE",
  ABOUT = "ABOUT"
}
